### ISSUE TITLE
Tính năng Pull data không Pull được data liên quan đến Domain

### ISSUE THREAD

**Issue by thangnguyennang** [iwayvietnam/zimbra-multi-tenancy#41]
Tính năng Pull data (data gồm: cos, domain, account, alias, group) không Pull được data liên quan đến domain gồm account, alias, và group mà chỉ Pull được 2 data là cos và domain. Ghi chú:
* Tính năng được kiểm thử trên môi trường: Zimbra 8.0.7 (64-bit), CentOS 6.5 (64-bit), PHP 5.4, Drupal 7.34
* Trước khi thêm tính năng progressbar để hiển thị progress trong quá trình Pull data thì tính năng hoạt động bình thường
* Thông tin log trên module (ảnh đính kèm)
![pull-data-error1](https://cloud.githubusercontent.com/assets/1904694/5661064/a802892c-9759-11e4-9ed4-6dea30afb04e.png)

**Comment by laquyen05** [comment]
Đã test lại trên môi trường: Zimbra 7.2.7 (64-bit), CentOS 5.11 (64-bit), PHP 5.3, Drupal 7.34 thì thấy việc Pull các data liên quan đến COS, Domain, Account, Alias, Group bình thường không bị lỗi như đã mô tả ở trên.

**Comment by thangnguyennang** [comment]
Đã thực hiện test lại việc Pull data, tính năng Pull data hoạt động bình thường.
